---
- name: Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
    exclude: kernel*

- name: Install the required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages }}"

- name: Deploy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Create new users
  user:
    name: "{{ item }}"
    shell: /bin/bash
    home: "/home/{{ item }}"
    state: present
  with_items: "{{ new_users }}"
  notify: Distribute authorized key
