---
- hosts: web_servers
  become: yes

  roles:
    - role: common
      tags: common
    - role: mariadb
      tags: mariadb
    - role: application
      tags: app
    - role: nginx
      tags: nginx
